import {
  AlignCenterLogo,
  AlignLeftLogo,
  AlignRightLogo,
  BoldLogo,
  BulletListLogo,
  ColorFillLogo,
  ItalicLogo,
  LineSpacingLogo,
  LinkLogo,
  NumberListLogo,
  RemoveLinkLogo,
  RemoveListLogo,
  UnderlineDashedLogo,
  UnderlineLogo,
  UnderlineWavyLogo,
} from "./TypewriterIcons";

export const TypeWriterAssets = {
  alignCenterLogo: AlignCenterLogo,
  alignLeftLogo: AlignLeftLogo,
  alignRightLogo: AlignRightLogo,
  boldLogo: BoldLogo,
  italicLogo: ItalicLogo,
  lineSpacingLogo: LineSpacingLogo,
  underlineLogo: UnderlineLogo,
  underlineDashedLogo: UnderlineDashedLogo,
  underlineWavyLogo: UnderlineWavyLogo,
  colorFillLogo: ColorFillLogo,
  linkLogo: LinkLogo,
  removeLinkLogo: RemoveLinkLogo,
  numberListLogo: NumberListLogo,
  bulletListLogo: BulletListLogo,
  removeListLogo: RemoveListLogo,
};
